name: ci:test
on:
  - push
  - pull_request
jobs:
  test:
    name: Continuous integration (test)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
      - run: npm test
